Repository rolling-scopes/rsschool-app, pull requests merged in 2022-09, with the labels that each got.

#1700 Fix: score columns filtering on Enter keypress
  client/src/modules/Score/components/ScoreTable/index.tsx
Labels: deploy

#1695 feat/profile updates
  client/src/__tests__/ProfilePage.test.tsx
  client/src/components/Header.tsx
  client/src/components/Profile/AboutCard.tsx
  client/src/components/Profile/CommonCard.tsx
  client/src/components/Profile/CommonCardWithSettingsModal.tsx
  client/src/components/Profile/ContactsCard.tsx
  client/src/components/Profile/ContactsCardForm.tsx
  client/src/components/Profile/CoreJsIviewsModal.tsx
  client/src/components/Profile/DiscordCard.tsx
  client/src/components/Profile/EducationCard.tsx
  client/src/components/Profile/EnglishCard.tsx
  client/src/components/Profile/MainCard.tsx
  client/src/components/Profile/MentorStatsCard.tsx
  client/src/components/Profile/PermissionsSettingsDrawer.tsx
  client/src/components/Profile/ProfileSettingsDrawer.tsx
  client/src/components/Profile/ProfileSettingsModal.tsx
  client/src/components/Profile/PublicFeedbackCard.tsx
  client/src/components/Profile/StudentStatsCard.tsx
  client/src/components/Profile/__test__/AboutCard.test.tsx
  client/src/components/Profile/__test__/CommonCard.test.tsx
  client/src/components/Profile/__test__/CommonCardWithSettingsModal.test.tsx
  client/src/components/Profile/__test__/ContactsCard.test.tsx
  client/src/components/Profile/__test__/ContactsCardForm.test.tsx
  client/src/components/Profile/__test__/EducationCard.test.tsx
  client/src/components/Profile/__test__/EnglishCard.test.tsx
  client/src/components/Profile/__test__/MainCard.test.tsx
  client/src/components/Profile/__test__/MentorStatsCard.test.tsx
  client/src/components/Profile/__test__/PermissionsSettingsDrawer.test.tsx
  client/src/components/Profile/__test__/ProfileSettingsDrawer.test.tsx
  client/src/components/Profile/__test__/ProfileSettingsModal.test.tsx
  client/src/components/Profile/__test__/PublicFeedbackCard.test.tsx
  client/src/components/Profile/__test__/StudentStatsCard.test.tsx
  client/src/components/Profile/__test__/__snapshots__/AboutCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/CommonCardWithSettingsModal.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/ContactsCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/ContactsCardForm.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/CoreJsIviewsCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/EducationCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/EnglishCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/MainCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/MentorStatsCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PermissionsSettingsDrawer.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PreScreeningIviewCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/ProfileSettingsDrawer.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/ProfileSettingsModal.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PublicFeedbackCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap
  client/src/pages/profile/index.tsx
  client/src/services/user.ts
Labels: deploy

#1709 feat: add submitText and validations fields to course task
  client/src/api/api.ts
  client/src/components/CrossCheck/SubmittedStatus.tsx
  client/src/components/Forms/ScoreInput.tsx
  client/src/components/Table/renderers.tsx
  client/src/modules/Course/pages/Student/CrossCheckSubmit/index.tsx
  client/src/modules/CourseManagement/components/CourseTaskModal/index.tsx
  client/src/modules/Home/pages/HomePage/index.tsx
  client/src/modules/Schedule/components/ManageEventModalForm/ManageEventForm.tsx
  client/src/modules/StudentDashboard/components/MentorCard.tsx
  client/src/pages/course/admin/tasks.tsx
  client/src/pages/course/mentor/submit-review.tsx
  client/src/pages/course/student/auto-test.tsx
  client/src/pages/course/student/cross-check-review2.tsx
  client/src/pages/course/submit-scores.tsx
  client/src/services/alerts.ts
  client/src/services/course.ts
  nestjs/src/courses/course-tasks/course-tasks.controller.ts
  nestjs/src/courses/course-tasks/course-tasks.service.ts
  nestjs/src/courses/course-tasks/dto/course-task.dto.ts
  nestjs/src/courses/course-tasks/dto/create-course-task.dto.ts
  nestjs/src/courses/course-tasks/dto/update-course-task.dto.ts
  nestjs/src/spec.json
  server/src/migrations/1662275601017-CourseTask.ts
  server/src/migrations/index.ts
  server/src/models/courseTask.ts
  server/src/repositories/courseTask.repository.ts
  server/src/routes/course/index.ts
  server/src/routes/course/schedule.ts
  server/src/routes/course/tasks/getCourseTask.ts
  server/src/routes/course/tasks/getCourseTasksDetailsForSchedule.ts
  server/src/routes/course/tasks/index.ts
Labels: deploy

#1710 feat: give access to edit course to course managers
  client/src/api/api.ts
  client/src/components/Sider/data/menuItems.tsx
  client/src/pages/admin/courses.tsx
  client/src/services/courses.ts
  client/src/services/models.ts
  nestjs/src/courses/courses.controller.ts
  nestjs/src/courses/courses.service.ts
  nestjs/src/courses/dto/index.ts
  nestjs/src/courses/dto/update-course.dto.ts
  nestjs/src/discord-servers/discord-servers.controller.ts
  nestjs/src/spec.json
  server/src/routes/course/index.ts
Labels: area:course, deploy

#1674 fix: don't allow submit any codewars username
  client/src/pages/course/student/auto-test.tsx
  docs/platform/tasks.md
Labels: code:client, area:docs

#1714 feat: add iCalendar Support
  .prettierignore
  client/src/api/api.ts
  client/src/modules/Schedule/components/SettingsDrawer/SettingsDrawer.tsx
  client/src/modules/Schedule/components/SettingsDrawer/TimeZone.tsx
  client/src/modules/Schedule/components/SettingsPanel/SettingsPanel.tsx
  client/src/modules/Schedule/pages/SchedulePage/index.tsx
  client/src/pages/course/admin/tasks.tsx
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/src/auth/auth.module.ts
  nestjs/src/auth/auth.service.spec.ts
  nestjs/src/auth/auth.service.ts
  nestjs/src/config/config.service.ts
  nestjs/src/core/core.module.ts
  nestjs/src/core/jwt/jwt.service.ts
  nestjs/src/courses/course-schedule/course-icalendar.controller.ts
  nestjs/src/courses/course-schedule/course-icalendar.service.ts
  nestjs/src/courses/course-schedule/dto/course-schedule-hash.dto.ts
  nestjs/src/courses/course-schedule/dto/index.ts
  nestjs/src/courses/course-schedule/index.ts
  nestjs/src/courses/course-tasks/course-tasks.controller.ts
  nestjs/src/courses/course-tasks/course-tasks.service.ts
  nestjs/src/courses/course-tasks/dto/course-task-detailed.dto.ts
  nestjs/src/courses/courses.module.ts
  nestjs/src/spec.json
  server/src/routes/course/events.ts
  server/src/routes/course/index.ts
Labels: 🚀 feature, area:schedule, deploy

#1723 feat: nextjs 12.3.0 and cdk update
  client/.eslintrc.js
  client/jest.config.js
  client/lambda/app.ts
  client/lambda/eventToReqRes.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/__snapshots__/ProfilePage.test.tsx.snap
  client/src/components/Forms/GithubPrInput.tsx
  client/src/components/Forms/ModalForm.tsx
  client/src/components/Forms/__tests__/__snapshots__/CourseTaskSelect.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/ProfileSettingsModal.test.tsx.snap
  client/src/components/StudentSearch.tsx
  client/src/components/Table/sorters.ts
  client/src/components/__tests__/__snapshots__/CrossCheckComments.test.tsx.snap
  client/src/components/useLoading.tsx
  client/src/components/withGoogleMaps.tsx
  client/src/domain/user.ts
  client/src/middleware.ts
  client/src/modules/Home/data/getServerSideProps.ts
  client/src/modules/Notifications/components/Consents.tsx
  client/src/modules/Opportunities/components/DataTextValue.tsx
  client/src/modules/Opportunities/pages/EditPage/index.tsx
  client/src/modules/Opportunities/pages/PublicPage/index.tsx
  client/src/modules/Schedule/components/ManageEventModalForm/ManageEventForm.tsx
  client/src/modules/Schedule/components/ManageEventModalForm/ManageEventModalForm.tsx
  client/src/modules/Score/components/ScoreTable/index.tsx
  client/src/modules/Score/hooks/types.ts
  client/src/modules/Score/hooks/useScorePaging.tsx
  client/src/pages/_document.tsx
  client/src/pages/admin/registrations.tsx
  client/src/pages/course/student/dashboard.tsx
  client/src/pages/registry/epamlearningjs.tsx
  client/src/services/cdn.ts
  client/src/services/check.ts
  client/src/services/course.ts
  client/src/services/files.ts
  client/src/services/gratitude.ts
  client/src/services/mentorRegistry.ts
  client/src/services/models.ts
  client/src/services/validators.ts
  client/tsconfig.json
  common/types/pagination/index.ts
  nestjs/src/courses/score/score.controller.ts
  nestjs/src/courses/score/score.service.ts
  package-lock.json
  package.json
  server/src/routes/course/certificates.ts
  server/src/routes/course/score/getScoreCsv.ts
  server/src/services/aws.service.ts
  server/src/services/score/score.service.ts
  setup/cdk/DockerFunctionConstruct.ts
  setup/cdk/Stack.ts
  setup/cdk/package-lock.json
  setup/cdk/package.json
Labels: deploy

#1730 feat: add Jury team badge
  client/public/static/svg/badges/JuryTeam.svg
  client/src/configs/heroes-badges.ts
  nestjs/src/gratitudes/dto/badge.dto.ts
  nestjs/src/gratitudes/gratitudes.service.ts
Labels: code:client

#1759 Restore broken validation on expel comment
  client/src/components/CommentModal.tsx
Labels: deploy
