Repository rolling-scopes/rsschool-app, pull requests merged in 2022-05, with the labels that each got.

#1366 chore(deps): update dependency moment to 2.29.2 [security]
  client/package-lock.json
  client/package.json
Labels: renovate

#1396 chore(deps): update dependency async to 3.2.2 [security]
  nestjs/package-lock.json
  nestjs/package.json
Labels: renovate

#1379 chore(deps): update dependency minimist to 1.2.6 [security]
  client/package-lock.json
  nestjs/package-lock.json
  nestjs/package.json
Labels: renovate

#1401 feat: redisign schedule timezone
  client/src/components/Schedule/SettingsDrawer/SettingsDrawer.tsx
  client/src/components/Schedule/SettingsDrawer/ShowTableColumns.tsx
  client/src/components/Schedule/SettingsDrawer/TimeZone.tsx
  client/src/components/Schedule/SettingsPanel/SettingsPanel.tsx
  client/src/components/Schedule/SettingsPanel/TimezoneSelect.tsx
  client/src/components/Schedule/useScheduleSettings.ts
Labels: area:schedule, code:client, deploy

#1425 feat: update solidarity component
  client/public/static/svg/solidarityUkraine.svg
  client/src/components/Header.tsx
  client/src/components/SolidarityUkraine.tsx
  docs/platform/adding-tests.md
  docs/platform/img/adding-tests-1.png
  docs/platform/img/adding-tests-2.png
  docs/platform/img/adding-tests-3.png
  docs/platform/img/adding-tests-4.png
Labels: code:client

#1452 fix: score table bugs
  client/src/modules/Score/components/ScoreTable/index.tsx
  client/src/modules/Score/data/getColumns.tsx
Labels: deploy
