Repository rolling-scopes/rsschool-app, pull requests merged in 2022-08, with the labels that each got.

#1626 refactor: change margin of pages
  client/src/pages/course/student/cross-check-review.tsx
  client/src/pages/course/student/dashboard.tsx
Labels: deploy

#1620 [CV Update] Update consent modal
  client/package-lock.json
  client/package.json
  client/src/__mocks__/setupJest.ts
  client/src/modules/Opportunities/components/EditViewResume.tsx
  client/src/modules/Opportunities/components/NoConsentView.tsx
  client/src/modules/Opportunities/components/NoConsentViewCV.tsx
  client/src/modules/Opportunities/components/__tests__/NoConsentView.test.tsx
  docs/platform/cv.md
  docs/platform/img/cv/header-dropdown.JPG
  docs/platform/img/cv/no-consent-modal.JPG
  docs/platform/img/cv/no-consent.JPG
Labels: area:opportunities, deploy

#1486 chore: update dependencies
  .github/workflows/pull_request.yml
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/ProfilePage.test.tsx
  client/src/__tests__/__snapshots__/ProfilePage.test.tsx.snap
  client/src/components/Forms/__tests__/CourseTaskSelect.test.tsx
  client/src/components/Forms/__tests__/__snapshots__/CourseTaskSelect.test.tsx.snap
  client/src/components/Profile/AboutCard.tsx
  client/src/components/Profile/ContactsCard.tsx
  client/src/components/Profile/CoreJsIviewsCard.tsx
  client/src/components/Profile/CoreJsIviewsModal.tsx
  client/src/components/Profile/EnglishCard.tsx
  client/src/components/Profile/__test__/AboutCard.test.tsx
  client/src/components/Profile/__test__/CommonCard.test.tsx
  client/src/components/Profile/__test__/ContactsCard.test.tsx
  client/src/components/Profile/__test__/CoreJsIviewsCard.test.tsx
  client/src/components/Profile/__test__/CoreJsIviewsModal.test.tsx
  client/src/components/Profile/__test__/EducationCard.test.tsx
  client/src/components/Profile/__test__/EnglishCard.test.tsx
  client/src/components/Profile/__test__/MainCard.test.tsx
  client/src/components/Profile/__test__/MentorStatsCard.test.tsx
  client/src/components/Profile/__test__/MentorStatsModal.test.tsx
  client/src/components/Profile/__test__/PermissionsSettingsDrawer.test.tsx
  client/src/components/Profile/__test__/PreScreeningIviewCard.test.tsx
  client/src/components/Profile/__test__/PreScreeningIviewModal.test.tsx
  client/src/components/Profile/__test__/ProfileSettingsDrawer.test.tsx
  client/src/components/Profile/__test__/PublicFeedbackCard.test.tsx
  client/src/components/Profile/__test__/PublicFeedbackModal.test.tsx
  client/src/components/Profile/__test__/StudentStatsCard.test.tsx
  client/src/components/Profile/__test__/StudentStatsModal.test.tsx
  client/src/components/Profile/__test__/__snapshots__/AboutCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/CommonCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/ContactsCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/CoreJsIviewsCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/CoreJsIviewsModal.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/EducationCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/EnglishCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/MainCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/MentorStatsCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/MentorStatsModal.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PermissionsSettingsDrawer.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PreScreeningIviewCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PreScreeningIviewModal.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/ProfileSettingsDrawer.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PublicFeedbackCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/PublicFeedbackModal.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap
  client/src/components/Profile/__test__/__snapshots__/StudentStatsModal.test.tsx.snap
  client/src/components/__tests__/CrossCheckComments.test.tsx
  client/src/components/__tests__/__snapshots__/CrossCheckComments.test.tsx.snap
  client/src/setupJest.ts
Labels: deploy

#1651 fix: pin bumblebee dependencies
  tools/bumblebee/package-lock.json
  tools/bumblebee/package.json
Labels: code:bumblebee

#1656 chore(deps): update nest monorepo
  CONTRIBUTING.md
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/src/alerts/alerts.service.ts
  nestjs/src/auth/auth-user.model.spec.ts
  nestjs/src/auth/auth-user.model.ts
  nestjs/src/auth/auth.module.ts
  nestjs/src/auth/auth.repository.ts
  nestjs/src/auth/auth.service.spec.ts
  nestjs/src/auth/auth.service.ts
  nestjs/src/certificates/certificates.service.ts
  nestjs/src/core/subscribers/base-subscriber.ts
  nestjs/src/courses/course-access.service.ts
  nestjs/src/courses/course-events/course-events.service.ts
  nestjs/src/courses/course-tasks/course-tasks.service.ts
  nestjs/src/courses/courses.service.ts
  nestjs/src/courses/students/feedbacks/feedbacks.service.ts
  nestjs/src/courses/students/students.service.ts
  nestjs/src/courses/task-solutions/task-solutions.service.ts
  nestjs/src/cross-check/cross-check.service.ts
  nestjs/src/disciplines/disciplines.service.ts
  nestjs/src/gratitudes/gratitudes.service.ts
  nestjs/src/notifications/notifications.service.ts
  nestjs/src/opportunities/opportunities.service.ts
  nestjs/src/ormconfig.ts
  nestjs/src/user-groups/user-groups.service.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/dataSource.ts
  server/src/dataSourceOptions.ts
  server/src/models/courseEvent.ts
  server/src/models/courseTask.ts
  server/src/repositories/crossCheck.repository.ts
  server/src/repositories/stageInterview.repository.ts
  server/src/routes/common.ts
  server/src/routes/course/index.ts
  server/src/routes/course/score/getScore.ts
  server/src/routes/course/score/index.ts
  server/src/routes/course/taskArtefact.ts
  server/src/routes/course/tasks/createCourseTaskDistribution.ts
  server/src/routes/me.ts
  server/src/routes/registry/index.ts
  server/src/routes/task/index.ts
  server/src/services/course.service.ts
  server/src/services/interview.service.ts
  server/src/services/repository.service.ts
  server/src/services/score/score.service.ts
  server/src/services/tasks.service.ts
Labels: renovate, deploy

#1658 chore(deps): update dependency prettier to v2.7.1
  package-lock.json
  package.json
Labels: renovate

#1660 chore: update nestjs
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/src/core/pino.ts
  server/src/migrations/1661087975938-Discipline.ts
  server/src/migrations/index.ts
  server/src/models/index.ts
Labels: deploy

#1659 chore: update cdk
  setup/cdk/package-lock.json
  setup/cdk/package.json
Labels: deploy

#1666 chore(deps): update dependency @types/jest to v28.1.7
  client/package-lock.json
  client/package.json
Labels: renovate

#1668 chore(deps): update dependency @types/node to v16.11.52
  client/package-lock.json
  client/package.json
  nestjs/package-lock.json
  nestjs/package.json
Labels: renovate

#1669 chore(deps): update dependency pino-pretty to v9
  nestjs/package-lock.json
  nestjs/package.json
Labels: renovate

#1667 chore(deps): update dependency @types/lodash to v4.14.184
  client/package-lock.json
  client/package.json
Labels: renovate

#1664 Feature/discipline
  client/src/api/api.ts
  client/src/components/Sider/data/menuItems.tsx
  client/src/modules/Discipline/components/DisciplineModal.tsx
  client/src/modules/Discipline/components/DisciplineTable.tsx
  client/src/modules/Discipline/pages/DisciplinePage.tsx
  client/src/modules/InterviewQuestions/data/getServerSideProps.ts
  client/src/pages/admin/courses.tsx
  client/src/pages/admin/disciplines.tsx
  client/src/pages/admin/events.tsx
  client/src/pages/admin/tasks.tsx
  client/src/services/courses.ts
  client/src/services/event.ts
  client/src/services/models.ts
  client/src/services/task.ts
  nestjs/src/courses/courses.service.ts
  nestjs/src/courses/dto/course.dto.ts
  nestjs/src/profile/profile.service.ts
  nestjs/src/spec.json
  server/src/migrations/1661106736439-Disciplines.ts
  server/src/migrations/1661107174477-Disciplines.ts
  server/src/migrations/index.ts
  server/src/models/course.ts
  server/src/models/event.ts
  server/src/models/index.ts
  server/src/models/task.ts
  server/src/routes/events/index.ts
  server/src/routes/index.ts
  server/src/routes/tasks/index.ts
Labels: deploy

#1670 chore(deps): lock file maintenance
  client/package-lock.json
  nestjs/package-lock.json
  package-lock.json
Labels: renovate

#1675 fix: change triggers for Schedule settings tooltip
  client/src/modules/Schedule/components/SettingsDrawer/SettingsDrawer.tsx
Labels: 🐞 bug, area:schedule, code:client

#1677 feat(schedule): use standard course task modal
  client/src/api/api.ts
  client/src/components/Table/renderers.tsx
  client/src/modules/CourseManagement/components/CourseTaskModal/index.tsx
  client/src/modules/CourseManagement/components/CoursesListModal/index.tsx
  client/src/modules/Schedule/components/EventDetails/TaskDetails.tsx
  client/src/modules/Schedule/components/EventDetails/index.ts
  client/src/modules/Schedule/components/ManageEventModalForm/ManageEventForm.tsx
  client/src/modules/Schedule/components/ManageEventModalForm/ManageEventModalForm.tsx
  client/src/modules/Schedule/components/SettingsPanel/AddEventButton.tsx
  client/src/modules/Schedule/components/SettingsPanel/SettingsPanel.tsx
  client/src/modules/Schedule/pages/SchedulePage/index.tsx
  client/src/pages/course/admin/tasks.tsx
  client/src/pages/course/mentor/submit-review.tsx
  client/src/services/course.ts
  nestjs/src/courses/course-schedule/course-schedule.controller.ts
  nestjs/src/courses/course-schedule/course-schedule.service.ts
  nestjs/src/courses/course-schedule/dto/course-copy-from.dto.ts
  nestjs/src/courses/course-tasks/dto/course-task.dto.ts
  nestjs/src/courses/course-tasks/dto/create-course-task.dto.ts
  nestjs/src/cross-check/tasks-filtering.ts
  nestjs/src/schedule/schedule.service.ts
  nestjs/src/spec.json
  server/src/models/courseEvent.ts
  server/src/models/courseTask.ts
  server/src/routes/course/schedule.ts
  server/src/routes/validators.ts
  server/src/services/tasks.service.ts
Labels: area:schedule, deploy

#1688 chore(deps): update dependency moment-timezone to 0.5.35 [security]
  client/package-lock.json
  client/package.json
Labels: renovate

#1690 chore(deps): update dependency @types/jest to v28.1.8
  client/package-lock.json
  client/package.json
  nestjs/package-lock.json
  nestjs/package.json
Labels: renovate
