Repository rolling-scopes/rsschool-app, pull requests merged in 2022-06, with the labels that each got.

#1451 feat: add weight column; rename score and name columns to more clear ones
  client/src/components/Schedule/TableView/TableView.tsx
  client/src/components/Schedule/constants.ts
  client/src/components/Table/renderers.tsx
Labels: area:schedule, area:student, code:client

#1479 fix: courses visibility
  client/src/modules/Opportunities/components/CoursesSection.tsx
  client/src/modules/Opportunities/components/PublicLink.tsx
  client/src/modules/Opportunities/components/ViewCV.tsx
  docs/platform/cv.md
  nestjs/src/opportunities/opportunities.service.ts
Labels: deploy

#1498 feat: add possibility to rejoin course after leaving
  client/src/api/api.ts
  client/src/components/Profile/StudentStatsCard.tsx
  client/src/components/Profile/__test__/__snapshots__/StudentStatsCard.test.tsx.snap
  client/src/pages/course/mentor/expel-student.tsx
  client/src/services/course.ts
  common/models/profile.ts
  nestjs/src/courses/course-access.service.ts
  nestjs/src/courses/courses.controller.ts
  nestjs/src/courses/dto/index.ts
  nestjs/src/courses/dto/leave-course.dto.ts
  nestjs/src/spec.json
  server/src/routes/course/student.ts
  server/src/routes/profile/student-stats.ts
Labels: deploy

#1514 fix: hide old events using endDate instead of startDate
  client/src/pages/course/schedule.tsx
Labels: 🐞 bug, code:client

#1527 chore(deps): update dependency jpeg-js to 0.4.4 [security]
  client/package-lock.json
  client/package.json
Labels: renovate

#1537 fix: order tasks by studentEndDate + name
  nestjs/src/courses/courseTasks/course-tasks.service.ts
Labels: code:server

#1539 fix: remove firstDayOfTheWeek setting
  client/src/components/Schedule/SettingsDrawer/SettingsDrawer.tsx
  client/src/components/Schedule/SettingsDrawer/TimeZone.tsx
  client/src/components/Schedule/useScheduleSettings.ts
Labels: area:schedule, code:client

#1538 fix: show all the timezones in the schedule
  client/src/components/Schedule/SettingsDrawer/TimeZone.tsx
  client/src/configs/timezones.ts
Labels: area:schedule, code:client, deploy

#1545 fix: change test result message
  server/src/routes/course/taskVerification.ts
Labels: 🐞 bug

#1488 fix: discord rate limiter
  client/src/api/api.ts
  client/src/pages/gratitude.tsx
  nestjs/src/gratitudes/dto/create-gratitude.dto.ts
  nestjs/src/gratitudes/gratitudes.controller.ts
  nestjs/src/gratitudes/gratitudes.service.ts
  nestjs/src/spec.json
Labels: 🐞 bug, area:feedback, deploy
