Repository rolling-scopes/rsschool-app, pull requests merged in 2022-10, with the labels that each got.

#1764 feat: change the process of creating repositories
  server/src/services/repository.service.ts
Labels: area:github

#1767 Add tests for Opportunities module
  client/package-lock.json
  client/package.json
  client/src/modules/Opportunities/components/AvatarCv/index.test.tsx
  client/src/modules/Opportunities/components/EditCv/ContactsForm/index.test.tsx
  client/src/modules/Opportunities/components/EditCv/GeneralInfoForm/index.test.tsx
  client/src/modules/Opportunities/components/EditCv/GeneralInfoForm/index.tsx
  client/src/modules/Opportunities/components/EditCv/VisibleCoursesForm/index.test.tsx
  client/src/modules/Opportunities/components/EditCv/index.test.tsx
  client/src/modules/Opportunities/components/EditCv/index.tsx
  client/src/modules/Opportunities/components/EditViewCv/index.test.tsx
  client/src/modules/Opportunities/components/EditViewCv/index.tsx
  client/src/modules/Opportunities/components/ExpirationTooltip/index.test.tsx
  client/src/modules/Opportunities/components/ExpirationTooltip/index.tsx
  client/src/modules/Opportunities/components/Link/index.test.tsx
  client/src/modules/Opportunities/components/Link/index.tsx
  client/src/modules/Opportunities/components/NameTitle/index.test.tsx
  client/src/modules/Opportunities/components/PublicLink/index.test.tsx
  client/src/modules/Opportunities/components/PublicLink/index.tsx
  client/src/modules/Opportunities/components/SidebarSectionHeader/index.test.tsx
  client/src/modules/Opportunities/components/StudentStatus/index.test.tsx
  client/src/modules/Opportunities/components/StudentStatus/index.tsx
  client/src/modules/Opportunities/components/ViewCv/AboutSection/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/ActionButtons/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/ActionButtons/index.tsx
  client/src/modules/Opportunities/components/ViewCv/BaseSection/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/ContactsSection/ContactsList/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/ContactsSection/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/CoursesSection/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/CoursesSection/index.tsx
  client/src/modules/Opportunities/components/ViewCv/DataTextValue/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/FeedbackSection/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/FeedbackSection/index.tsx
  client/src/modules/Opportunities/components/ViewCv/GratitudeSection/GratitudeList/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/GratitudeSection/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/PersonalSection/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/index.test.tsx
  client/src/modules/Opportunities/components/ViewCv/index.tsx
  client/src/modules/Opportunities/data/__snapshots__/getPersonalToRender.test.tsx.snap
  client/src/modules/Opportunities/data/getContactsToRender.test.tsx
  client/src/modules/Opportunities/data/getPersonalToRender.test.tsx
  client/src/modules/Opportunities/hooks/useExpiration.test.tsx
  client/src/modules/Opportunities/hooks/useResumeData.test.tsx
  client/src/modules/Opportunities/hooks/useViewData.test.tsx
  client/src/modules/Opportunities/hooks/useViewData.tsx
  client/src/modules/Opportunities/transformers/splitDataForForms.test.ts
  client/src/modules/Opportunities/transformers/transformFieldsData.test.ts
  client/src/modules/Opportunities/transformers/transformInitialCvData.test.ts
  client/src/modules/Schedule/components/FilteredTags/FilteredTags.test.tsx
  docs/platform/cv.md
  docs/platform/img/cv/cv-empty.JPG
  docs/platform/img/cv/cv-form-buttons.JPG
  docs/platform/img/cv/cv-form-filled-1.JPG
  docs/platform/img/cv/cv-form-filled.JPG
  docs/platform/img/cv/cv-view-filled.JPG
  docs/platform/img/cv/cv-view-print.JPG
  docs/platform/img/cv/edit-cv-buttons.JPG
  docs/platform/img/cv/view-control-buttons.JPG
  docs/platform/img/cv/view-delete-cv.JPG
Labels: area:opportunities

#1783 Change students pages background
  client/src/pages/course/student/auto-test.tsx
  client/src/pages/course/student/dashboard.tsx
  client/src/pages/course/student/interviews.tsx
Labels: deploy

#1791 fix: spelling
  client/src/pages/course/student/auto-test.tsx
Labels: code:client, user experience

#1798 Update mentorship text
  client/src/modules/Registry/components/MentorStepAbout/index.tsx
Labels: deploy

#1796 feat(schedule): move setting buttons under dropdown
  client/src/modules/Schedule/components/AdditionalActions/AdditionalActions.test.tsx
  client/src/modules/Schedule/components/AdditionalActions/AdditionalActions.tsx
  client/src/modules/Schedule/components/AdditionalActions/helpers.ts
  client/src/modules/Schedule/components/AdditionalActions/index.tsx
  client/src/modules/Schedule/components/FilteredTags/FilteredTags.tsx
  client/src/modules/Schedule/components/SettingsPanel/ManageCsvButtons.tsx
  client/src/modules/Schedule/components/SettingsPanel/SettingsPanel.test.tsx
  client/src/modules/Schedule/components/SettingsPanel/SettingsPanel.tsx
  client/src/modules/Schedule/components/SettingsPanel/helpers.ts
  client/src/modules/Schedule/components/SettingsPanel/index.ts
  client/src/modules/Schedule/components/StatusTabs/StatusTabs.tsx
  client/src/modules/Schedule/components/TableView/TableView.tsx
  client/src/modules/Schedule/pages/SchedulePage/index.tsx
Labels: deploy
