Repository rolling-scopes/rsschool-app, pull requests merged in 2023-02, with the labels that each got.

#1990 feat: add dementor role
  client/src/api/api.ts
  client/src/components/withSession.tsx
  client/src/domain/user.test.tsx
  client/src/domain/user.ts
  client/src/modules/Course/contexts/SessionContext.tsx
  client/src/modules/Score/data/isExportEnabled.ts
  client/src/pages/admin/user-group.tsx
  client/src/pages/course/admin/users.tsx
  client/src/pages/course/interview/[type]/feedback.tsx
  client/src/pages/course/mentor/dashboard.tsx
  client/src/pages/course/mentor/expel-student.tsx
  client/src/pages/course/mentor/feedback/index.tsx
  client/src/pages/course/mentor/interview-corejs.tsx
  client/src/pages/course/mentor/interview-technical-screening.tsx
  client/src/pages/course/mentor/students.tsx
  client/src/pages/course/student/cross-check-review.tsx
  client/src/pages/course/student/cross-check-submit.tsx
  client/src/services/course.ts
  client/src/services/models.ts
  common/models/index.ts
  common/models/user-group.ts
  nestjs/src/auth/auth-user.model.ts
  nestjs/src/spec.json
  nestjs/src/user-groups/dto/create-user-group.dto.ts
  nestjs/src/user-groups/dto/user-group.dto.ts
  server/src/migrations/1675245424426-UserGroup.ts
  server/src/migrations/index.ts
  server/src/models/courseUser.ts
  server/src/models/session.ts
  server/src/models/userGroup.ts
  server/src/routes/course/user.ts
  server/src/services/course.service.ts
Labels: deploy

#2007 Fix: Excessive modal appearance on creation of CV
  client/src/api/api.ts
  client/src/modules/Opportunities/pages/EditPage/index.tsx
  nestjs/src/opportunities/dto/consent.dto.ts
  nestjs/src/opportunities/dto/give-consent-dto.ts
  nestjs/src/opportunities/opportunities.controller.ts
  nestjs/src/opportunities/opportunities.service.ts
  nestjs/src/spec.json
Labels: deploy

#2029 Implement solutions urls CVS download
  client/src/api/api.ts
  client/src/components/BadReview/BadReviewControllers.tsx
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/src/courses/cross-checks/course-cross-checks.controller.ts
  nestjs/src/courses/cross-checks/course-cross-checks.service.spec.ts
  nestjs/src/courses/cross-checks/course-cross-checks.service.ts
  nestjs/src/spec.json
Labels: area:course, deploy

#1950 feat: rebuild mentor registration form
  client/public/static/svg/logo-epam.svg
  client/public/static/svg/logo-github.svg
  client/public/static/svg/logo-rs.svg
  client/src/api/api.ts
  client/src/components/Icons/EpamLogoIcon.tsx
  client/src/components/Icons/GitHubLogoIcon.tsx
  client/src/components/Icons/RSLogoIcon.tsx
  client/src/components/Icons/index.tsx
  client/src/components/RegistartionPageLayout.tsx
  client/src/modules/Registry/components/AdditionalInfo/AdditionalInfo.test.tsx
  client/src/modules/Registry/components/AdditionalInfo/AdditionalInfo.tsx
  client/src/modules/Registry/components/ContactInfo/ContactInfo.test.tsx
  client/src/modules/Registry/components/ContactInfo/ContactInfo.tsx
  client/src/modules/Registry/components/Disciplines/Disciplines.test.tsx
  client/src/modules/Registry/components/Disciplines/Disciplines.tsx
  client/src/modules/Registry/components/Footer/Footer.tsx
  client/src/modules/Registry/components/Form/DoneSection/DoneSection.tsx
  client/src/modules/Registry/components/Form/GeneralSection/GeneralSection.tsx
  client/src/modules/Registry/components/Form/MentorshipSection/MentorshipSection.tsx
  client/src/modules/Registry/components/FormCard/FormCard.tsx
  client/src/modules/Registry/components/MentorRegistrationGeneral/index.tsx
  client/src/modules/Registry/components/MentorRegistrationMentorship/index.tsx
  client/src/modules/Registry/components/MentorStep/index.tsx
  client/src/modules/Registry/components/MentorStepAbout/index.tsx
  client/src/modules/Registry/components/MentorStepFooter/index.tsx
  client/src/modules/Registry/components/MentorStepRegistration/index.tsx
  client/src/modules/Registry/components/MentorStepSuccess/index.tsx
  client/src/modules/Registry/components/PersonalInfo/PersonalInfo.test.tsx
  client/src/modules/Registry/components/PersonalInfo/PersonalInfo.tsx
  client/src/modules/Registry/components/Preferences/Preferences.test.tsx
  client/src/modules/Registry/components/Preferences/Preferences.tsx
  client/src/modules/Registry/components/index.tsx
  client/src/modules/Registry/constants/index.ts
  client/src/modules/Registry/hooks/index.ts
  client/src/modules/Registry/hooks/useFormProps/useFormProps.ts
  client/src/modules/Registry/hooks/useMentorData/useMentorData.tsx
  client/src/modules/Registry/pages/Mentor/formData.ts
  client/src/modules/Registry/pages/Mentor/index.tsx
  client/src/services/user.ts
  nestjs/src/profile/dto/update-user.dto.ts
  nestjs/src/profile/profile.service.ts
  nestjs/src/spec.json
  server/src/migrations/1676139987317-User.ts
  server/src/migrations/index.ts
  server/src/models/data/available-languages.data.ts
  server/src/models/data/index.ts
  server/src/models/user.ts
  server/src/repositories/mentorRegistry.repository.ts
Labels: deploy

#2040 Deduplicate records in solutions urls csv
  nestjs/src/courses/cross-checks/course-cross-checks.service.spec.ts
  nestjs/src/courses/cross-checks/course-cross-checks.service.ts
Labels: area:course

#2031 Migrate course users endpoint
  client/src/api/api.ts
  client/src/pages/course/admin/users.tsx
  client/src/pages/course/student/dashboard.tsx
  nestjs/src/auth/auth.service.spec.ts
  nestjs/src/courses/course-users.service.ts
  nestjs/src/courses/course-users/course-users.controller.spec.ts
  nestjs/src/courses/course-users/course-users.controller.ts
  nestjs/src/courses/course-users/course-users.service.spec.ts
  nestjs/src/courses/course-users/course-users.service.ts
  nestjs/src/courses/course-users/dto/course-roles.dto.ts
  nestjs/src/courses/course-users/dto/course-user.dto.ts
  nestjs/src/courses/course-users/dto/update-user.dto.ts
  nestjs/src/courses/course-users/types.ts
  nestjs/src/courses/courses.module.ts
  nestjs/src/courses/index.ts
  nestjs/src/spec.json
  server/src/routes/course/index.ts
  server/src/routes/course/user.ts
Labels: area:tech, deploy

#2048 Fix: Allow course manager to see course mentors
  server/src/routes/profile/info.ts
  server/src/routes/profile/permissions.ts
Labels: area:profile, deploy
