Repository rolling-scopes/rsschool-app, pull requests merged in 2023-05, with the labels that each got.

#2143 Show mentors by discipline
  nestjs/src/disciplines/disciplines.controller.test.ts
  nestjs/src/disciplines/disciplines.module.ts
  nestjs/src/disciplines/disciplines.service.test.ts
  nestjs/src/disciplines/disciplines.service.ts
  nestjs/src/registry/registry.controller.ts
  nestjs/src/registry/registry.module.ts
  nestjs/src/registry/registry.service.ts
  server/src/routes/profile/permissions.ts
Labels: area:mentor

#2144 feat: add historical score in cross-check table
  client/src/api/api.ts
  client/src/pages/course/admin/cross-check-table.tsx
  nestjs/src/courses/cross-checks/course-cross-checks.service.ts
  nestjs/src/courses/cross-checks/dto/check-tasks-pairs.dto.ts
  nestjs/src/spec.json
  server/src/models/taskSolutionResult.ts
Labels: area:crosscheck

#2156 chore(deps): update dependency prettier to v2.8.8
  nestjs/package-lock.json
  nestjs/package.json
  package-lock.json
  package.json
Labels: renovate

#2149 feat: switch to neon database for staging
  docker-compose.yml
  nestjs/Dockerfile.lambda
  nestjs/src/ormconfig.ts
  server/.env.example
  server/Dockerfile.lambda
  server/src/config.ts
  server/src/dataSourceOptions.ts
Labels: deploy

#2146 Copy course tasks and events correctly
  server/src/services/course.service.ts
Labels: area:schedule, area:course

#2088 feat(course-management)/implement students list modals
  client/src/components/Student/CertificateCriteria.tsx
  client/src/components/Student/ExpelCriteria.tsx
  client/src/components/Student/index.ts
  client/src/modules/CourseManagement/components/CertificateCriteriaModal/CertificateCriteriaModal.test.tsx
  client/src/modules/CourseManagement/components/CertificateCriteriaModal/CertificateCriteriaModal.tsx
  client/src/modules/CourseManagement/components/ExpelCriteriaModal/ExpelCriteriaModal.test.tsx
  client/src/modules/CourseManagement/components/ExpelCriteriaModal/ExpelCriteriaModal.tsx
  client/src/modules/CourseManagement/components/SelectCourseTasks/SelectCourseTasks.test.tsx
  client/src/modules/CourseManagement/components/SelectCourseTasks/SelectCourseTasks.tsx
  client/src/modules/CourseManagement/components/index.ts
  client/src/pages/course/admin/students.tsx
Labels: deploy
