Repository rolling-scopes/rsschool-app, pull requests merged in 2023-04, with the labels that each got.

#2104 feat: add filter by type for tasks
  client/src/pages/admin/tasks.tsx
Labels: code:client

#2117 chore(deps): update dependency @nestjs/core to 9.0.5 [security]
  nestjs/package-lock.json
  nestjs/package.json
  server/src/models/student-feedback.ts
Labels: renovate

#2120 Remove scroll on Auto-tests page
  client/src/modules/AutoTest/pages/AutoTests/AutoTests.tsx
Labels: area:student

#2118 chore(deps): update dependency xml2js to 0.5.0 [security]
  nestjs/package-lock.json
  nestjs/package.json
  nestjs/src/core/paginate/index.ts
Labels: renovate
