Repository rolling-scopes/rsschool-app, pull requests merged in 2023-03, with the labels that each got.

#2052 fix(mentor registration): add course preselect from direct link
  client/src/modules/Registry/components/Cards/AdditionalInfo/AdditionalInfo.test.tsx
  client/src/modules/Registry/components/Cards/AdditionalInfo/AdditionalInfo.tsx
  client/src/modules/Registry/components/FormSections/GeneralSection/GeneralSection.test.tsx
  client/src/modules/Registry/components/FormSections/MentorshipSection/MentorshipSection.test.tsx
  client/src/modules/Registry/components/FormSections/MentorshipSection/MentorshipSection.tsx
  client/src/modules/Registry/hooks/useMentorData/useMentorData.tsx
  client/src/modules/Registry/pages/Mentor/Mentor.tsx
Labels: deploy

#2045 chore: update nestjs depenencies
  nestjs/package-lock.json
  nestjs/package.json
Labels: deploy

#2058 feat: validate email correctly
  client/src/components/Profile/ContactsCard.tsx
Labels: deploy

#2036 Fix: Previous course user name and roles appear in the modal
  client/src/components/Forms/ModalForm.tsx
  client/src/pages/course/admin/users.tsx
Labels: area:course, deploy

#2053 feat: migrate task verification endpoint to nestjs
  client/src/api/api.ts
  client/src/modules/AutoTest/hooks/useCourseTaskSubmit/useCourseTaskSubmit.test.ts
  client/src/modules/AutoTest/hooks/useCourseTaskSubmit/useCourseTaskSubmit.ts
  client/src/services/course.ts
  nestjs/src/cloud-api/cloud-api.module.ts
  nestjs/src/cloud-api/cloud-api.service.ts
  nestjs/src/courses/courses.module.ts
  nestjs/src/courses/score/index.ts
  nestjs/src/courses/score/score.service.ts
  nestjs/src/courses/score/write-score.service.ts
  nestjs/src/courses/task-verifications/dto/create-task-verification.dto.ts
  nestjs/src/courses/task-verifications/self-education.service.ts
  nestjs/src/courses/task-verifications/task-verifications.controller.ts
  nestjs/src/courses/task-verifications/task-verifications.service.ts
  nestjs/src/spec.json
  server/src/models/taskVerification.ts
  server/src/routes/course/index.ts
  server/src/routes/course/taskVerification.ts
Labels: deploy

#2086 chore(deps): update dependency webpack to 5.76.0 [security]
  nestjs/package-lock.json
  nestjs/package.json
Labels: renovate

#2089 Add successful save notification
  client/src/modules/Opportunities/components/EditCv/index.test.tsx
  client/src/modules/Opportunities/components/EditCv/index.tsx
Labels: area:opportunities, deploy

#2096 Allow course manager to see profiles of mentors from registry
  nestjs/src/courses/mentors/mentors.controller.ts
  server/src/routes/profile/permissions.ts
Labels: area:mentor, area:course
