Repository rolling-scopes/rsschool-app, pull requests merged in 2025-08, with the labels that each got.

#2791 Replace TwoTone icons with Outlined icons on the Home page
  client/src/modules/Home/data/links.tsx
Labels: priority:low, user experience, ⚔️padawans

#2792 chore(deps): update dependency koa to v2.16.2 [security]
  package-lock.json
  server/package.json
Labels: renovate

#2793 chore(deps): update dependency luxon to v2.5.2 [security]
  package-lock.json
  server/package.json
Labels: renovate

#2794 chore(deps): update dependency moment-timezone to v0.5.35 [security]
  package-lock.json
  server/package.json
Labels: renovate

#2805 fix: change attempts message explanation if strictAttemptsMode
  client/src/modules/AutoTest/hooks/useAttemptsMessage/useAttemptsMessage.test.ts
  client/src/modules/AutoTest/hooks/useAttemptsMessage/useAttemptsMessage.ts
Labels: area:autotests, ⚔️padawans
