Repository rolling-scopes/rsschool-app, pull requests merged in 2025-07, with the labels that each got.

#2750 refactor: rename getDiscordServerById endpoint to getInviteLinkByDiscordServerId with URL invite/:id
  client/src/api/api.ts
  client/src/pages/course/mentor/confirm.tsx
  nestjs/src/discord-servers/discord-servers.controller.ts
  nestjs/src/spec.json
Labels: ⚔️padawans

#2748 fix: change telegram link on the mentor's dashboard page
  client/src/modules/Mentor/components/Instructions/Instructions.tsx
  client/src/modules/Mentor/components/Instructions/constants.ts
  client/src/modules/Mentor/components/Instructions/renderers.tsx
  client/src/modules/Mentor/components/MentorDashboard/MentorDashboard.tsx
Labels: area:mentor, ⚔️padawans

#2754 fix: change style of tabs component and fix logic of handleTabChange
  client/src/pages/admin/mentor-registry.tsx
Labels: ⚔️padawans

#2761 fix: remove the element.group for correct display of selected radios answers
  client/src/modules/AutoTest/components/AttemptsAnswers/AttemptsAnswers.tsx
  client/src/modules/AutoTest/components/Question/Question.tsx
  client/src/pages/admin/auto-test-task/[taskId].tsx
Labels: area:autotests, ⚔️padawans

#2779 FIX: wrong colors for cross-check detailed view
  client/src/modules/CrossCheck/components/criteria/CrossCheckCriteria.tsx
  client/src/modules/CrossCheck/components/criteria/SubtaskCriteria.tsx
Labels: ⚔️padawans

#2780 Proper colors in dark theme for ScoreCard, Leaving course modal icon and tootip placement for the CV modal
  client/src/components/Profile/StudentLeaveCourse.tsx
  client/src/components/Profile/StudentStatsCard.tsx
  client/src/components/ScoreCard.tsx
  client/src/modules/Opportunities/components/NoConsentView/index.tsx
Labels: ⚔️padawans

#2788 Color theme config, scroll and textarea styles
  client/src/modules/Schedule/components/FilteredTags/FilteredTags.tsx
  client/src/modules/StudentDashboard/components/MainStatsCard.tsx
  client/src/providers/ThemeProvider.tsx
  client/src/styles/main.css
Labels: user experience, ⚔️padawans
